#!/bin/sh

systemctl daemon-reload &> /dev/null || true
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
xdg-icon-resource forceupdate --theme hicolor &> /dev/null || true
update-desktop-database -q || true