export const EMPTY_USER_PASS = "EMPTY_USER_PASS";
export const SERVICE_NOT_AVAILABLE = "SERVICE_NOT_AVAILABLE";
export const AUTH_FAILED = "AUTH_FAILED";
export const DISCONNECT_INACTIVE = "DISCONNECT_INACTIVE";
export const TIMEOUT_CONNECT = "TIMEOUT_CONNECT";
export const CANT_FETCH_REMOTE = "CANT_FETCH_REMOTE";
