export const DOWNLOAD_CONFIG = "DOWNLOAD_CONFIG";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const LAUNCH_OPENVPN = "LAUNCH_OPENVPN";
export const SUBSCRIBE_TO_EVENTS = "SUBSCRIBE_TO_EVENTS";
