#!/bin/sh
kill -2 $(ps aux | grep 'VPN.ht.app' | awk '{print $2}') || true
launchctl unload /Library/LaunchAgents/ht.vpn.client.plist || true
launchctl unload /Library/LaunchDaemons/ht.vpn.service.plist || true

rm -rf /var/run/vpnht.sock || true
rm -rf /var/lib/vpnht || true
rm -f /var/log/vpnht.log || true
kextunload -b net.sf.tuntaposx.tap || true
kextunload -b net.sf.tuntaposx.tun || true
rm -rf /Library/Extensions/tap.kext || true
rm -rf /Library/Extensions/tun.kext || true
rm -f /Library/LaunchDaemons/net.sf.tuntaposx.tap.plist || true
rm -f /Library/LaunchDaemons/net.sf.tuntaposx.tun.plist || true
rm -rf /usr/local/bin/vpnht-openvpn || true
rm -rf /usr/local/bin/vpnht-service || true
